name = "CoordRefSystems"
uuid = "b46f11dc-f210-4604-bfba-323c1ec968cb"
authors = ["Elias Carvalho <eliascarvdev@gmail.com>", "JÃºlio Hoffimann <julio.hoffimann@gmail.com> and contributors"]
version = "0.7.4"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
Random = "1.9"
Rotations = "1.7"
StaticArrays = "1.9"
Unitful = "1.19"
Zygote = "0.6"
julia = "1.9"
